# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Dependabot should not update Home Assistant as that should match the homeassistant key in hacs.json
      - dependency-name: "homeassistant"
      # Ignore patch updates for all other Python packages to reduce noise.
      # PRs will only be created for minor and major version bumps.
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
        # Except for these packages where we want to follow the full patch version
        exclude-patterns:
          - "intex-spa"
          - "aio-intex-spa"
    labels:
      - "Dependencies"
      - "Python"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Dependencies"
      - "GitHub Actions"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Dependencies"
      - "DevContainers"
