---
name: "Bug report"
description: "Report a bug with the integration"
labels: "Bug"
body:

- type: markdown
  attributes:
    value: Before you open a new issue, search through the existing issues to see if others have had the same problem.

- type: input
  attributes:
    label: "Version of the custom_component"
    description: "Paste the version of your intex_spa integration page from Settings > Devices & Services"
  validations:
    required: true

- type: textarea
  attributes:
    label: "System Health details"
    description: "Paste the data from the System Health card in Home Assistant (https://www.home-assistant.io/more-info/system-health#github-issues)"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Describe the issue"
    description: |
      A clear and concise description of what the issue is:
      * What behavior you do expect ?
      * How the integration actually behaves ?
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction steps
    description: "Without steps to reproduce, it will be hard to fix. It is very important that you fill out this part. Issues without it will be closed."
    placeholder: |
      1.
      2.
      3.
      ...
  validations:
    required: true

- type: textarea
  attributes:
    label: "Debug logs"
    description: |
      This step is mandatory.

      To enable debug logging:
      1. add the following in your Home Assistant `config/configuration.yaml`:
      ```yaml
      logger:
      default: warning # 'warning' is the default value
      logs:
          custom_components.intex_spa: debug
          intex_spa: debug
      ```
      2. restart Home Assistant
      3. and copy-paste here _everything_ from startup of Home Assistant to the point where you encounter the issue.

      FYI, HA logger docs: https://www.home-assistant.io/integrations/logger/
    render: shell
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have enabled debug logging for my installation.
        required: true
      - label: I have filled out the issue template to the best of my ability.
        required: true
      - label: This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
        required: true
      - label: This issue is not a duplicate issue of any [previous issues](https://github.com/mathieu-mp/homeassistant-intex-spa/issues?q=is%3Aissue)..
        required: true
